### ISSUE TITLE
Add a awesome, good looking and simple README.md

### ISSUE THREAD

**Issue by Nikitha2309** [Design-and-Code/Dope-Github-Readmes#28]
- Add a awesome, good looking and simple README.md

@DevrajDC Kindly approve the issue under **Hactober Fest 2021** and assign it to me as I have already worked on the same
Thanks & Regards,
[Nikitha Reddy ](https://nikitha2309.github.io/Portfolio/)

**Comment by DevrajDC** [comment]
Hey, you may create a PR now.

**Comment by Nikitha2309** [comment]
Thanks @DevrajDC 
I have already created a [PR](https://github.com/Design-and-Code/Dope-Github-Readmes/pull/29)
