### ISSUE TITLE
Want to add a dope readme

### ISSUE THREAD

**Issue by iamrahulmahato** [Design-and-Code/Dope-Github-Readmes#55]
Can i add my design readme file

**Comment by DevrajDC** [comment]
What do you mean by Design readme file?

**Comment by iamrahulmahato** [comment]
@DevrajDC yes

**Comment by iamrahulmahato** [comment]
@DevrajDC The PR is made #56  . Kindly review and merge it.
Thank You

**Comment by Greeshma2903** [comment]
Hello @iamrahulmahato, you can directly open a PR for your next contribution, we'll review it there and merge it accordingly. Closing this issue for now. 🙂
